spring:
  application:
    name: cloud-zuul  #应用程序名

server:
  port: 9092   #端口号

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/ #注册中心地址
info:
  app: zuul网关-9092