spring:
  application:
    name: cloud-consumer  #应用程序名

server:
  port: 9091
#  context-path:  /cloud-consumer

eureka:
  instance:
    hostname: cloud-consumer-9091
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/ #注册中心地址
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true

#eureka客户端ribbon刷新时间
#默认30s
#ribbon:
#  ServerListRefreshInterval=5000
#security:
#  basic:
#    enabled: true
#  user:
#    password: admin
#    name: admin
