spring:
  application:
    name: cloud-consumer  #应用程序名

server:
  port: 9091   #端口号

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/#注册中心地址
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true


#security:
#  basic:
#    enabled: true
#  user:
#    password: admin
#    name: admin
