spring:
  application:
    name: cloud-apiservice  #应用程序名

server:
  port: 9090   #端口号

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/  #注册中心地址
security:
  basic:
    enabled: true
  user:
    password: admin
    name: admin
