spring:
  application:
    name: cloud-apiservice  #应用程序名

server:
  port: 9090   #端口号

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/  #注册中心地址
#security:
#  basic:
#    enabled: true
#  user:
#    password: admin
#    name: admin
#management:
#  security:
#    enabled: false
#服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
#默认90s
#eureka.instance.lease-expiration-duration-in-seconds=15
#服务刷新时间配置，每隔这个时间会主动心跳一次
#默认30s
#eureka.instance.lease-renewal-interval-in-seconds=5